// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// liftoverr.cpp
cpp11::data_frame lift_over(std::string path, cpp11::strings chroms, cpp11::integers starts);
extern "C" SEXP _liftoverr_lift_over(SEXP path, SEXP chroms, SEXP starts) {
  BEGIN_CPP11
    return cpp11::as_sexp(lift_over(cpp11::as_cpp<cpp11::decay_t<std::string>>(path), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(chroms), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(starts)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_liftoverr_lift_over", (DL_FUNC) &_liftoverr_lift_over, 3},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_liftoverr(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
